version: "3"

services:
  web:
    image: httpd:latest
    volumes:
      - ./web/bin:/usr/local/apache2/htdocs 
    ports:
      - 80:80
      
  db:
    build: db
    ports:
      - 1433
    healthcheck:
      test: "exit 0"

  api:
    build: api
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:1433
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=120
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"
    ports:
      - "81:5000"
